import os
from typing import Optional
from TOPED_fsl_commands import TOPED  # script containing subprocess commands

"""
About this script:
The script is run in Windows and expects files located in windows directories. 
 
This script runs all linux commands as a subprocess using the TOPED class in TOPED_fsl_commands.py.
    The input data is read from your specified windows directory 'main_dir' and the final output is saved in the same directory. 
    All processing is done in a specified linux working directory. All files for each patient are saved there and then copied back to the respective folders in the windows directory.
To run the script you will need to specify the parameters in the configuration section below. 
Input files for topup and and eddy are identified through keywords specified in the IDENTIFIERS dictionary. 
    for each input type (e.g. b0, dwi stack, mask, acqp, bvecs, bvals, index), specify a keyword that is contained in the respective file names in your dataset. 
    This should be unique, i.e. if the keyword for the topup imain input is "b0", the script looks for files containing "b0" in the name and takes that as input. If there are multiple files containing "b0", an error is raised.
    The assumed directory strucure is seen below. The script looks for the input files in the 'patient' folders first, then in the common folder if not found in the patient folder.
    The structure of the main directory will be copied into the Linux working directory (i.e. the same folders and files will be generated).

Requirements:
- Python packages (os, re, typing, subprocess, shutil)
- FSL installed with an WSL distro. user needs to be configured. Make sure FSL can be run from the command line in WSL.


Supported file inputs:
    Topup:
    - b0 image (4D file containing multiple b0 volumes). nii.gz (compulsory)
    - acqparams.txt (PE directions) (compulsory)
    - configuration file (if not specified the default FSL config b02b0.cnf is used) .cnf (optional)
    Eddy:
    - dwi image (4D stack contaning whatever should be topup+eddy corrected). nii.gz (compulsory)
    - mask (typically brain mask, but i dont do brain so its whatever i guess). nii.gz (compulsory)
    - acqparams (assumed to be the same as for topup). (compulsory)
    - index (to match the dwi stack volumes to the acqparams lines). (compulsory)
    - bvecs (as generated by e.g. dcm2niix). make sure they match the full stack. (compulsory)
    - bvals (as generated by e.g. dcm2niix). make sure they match the full stack. (compulsory)
    - slspec (optional). 
    - JSON (optional) 
"""

# main_directory
# ├── patient_1
# │   ├── pt1_b0.nii.gz
# │   ├── pt1_dwi_stack.nii.gz  
# │   ├── pt1_mask.nii.gz
# │   └── ... (other patient-specific files, e.g. pt1_jsonfile.json)
# ├── patient_2
# │   ├── pt2_b0.nii.gz
# │   ├── pt2_dwi_stack.nii.gz 
# │   ├── pt2_mask.nii.gz
# │   └── ... (other patient-specific files)    
# └── common_files (optional)
#     ├── acqparams.txt 
#     ├── bvecs.txt
#     ├── bvals.txt
#     ├── index.txt
#     ├── slspec.txt
#     └── config.cnf

# names of folders are arbitrary. 
# The names of these folders are copied into the linux working directory and are used to identify the respective entries.
# a 'common_files' folder is optional. The purpose is is you e.g. have the same config file or acqparams/bvecs/bvals/index/slspec files for all patients.

# =======================================================================================================================================================
"""CONFIGURATION - Adjust these parameters according to your data""" # change things in this section!

#main directory in WINDOWS containing patient folders and common folder.
MAIN_DIR = r"C:\path\to\your\main_dir" # replace with path to your main_dir.

# folder inside main_dir that contains files which are common for all patients (e.g. acqparams, bvecs, bvals, index, slspec).
COMMON_FOLDER_NAME = "common_files" # replace with your path, or set to None if there is no common folder.
# The script looks in the patient folders first. if it does not find the required files there, it looks in the common folder. 


# Filename identifiers - Change the RHS here according to your own file naming conventions!!!  
# The script will look for files containing these keywords in the patient folders first (then in the common folder). 
IDENTIFIERS = {
    "b0": "b0.nii.gz",      # e.g. topup --imain. assumed to contain str 'b0' in the filename. 
    # the name of the b0 file determines the names of generated output files. 
    # a b0 file named 'patient1_ddmmyyyy_b0.nii.gz' will generate output files which all have the prefix 'patient1_ddmmyyyy'.
    "dwi": "stack.nii.gz",  # e.g. eddy --imain. DWI stack assumed to contain 'stack' in the filename. Should have the same prefix as the b0 file, e.g. 'patient1_ddmmyyyy_stack.nii.gz' to match with 'patient1_ddmmyyyy_b0.nii.gz'.
    "mask": "mask",         # eddy --mask. contains 'mask' in the filename.
    "bvec": "bvec", 
    "bval": "bval",
    "index": "index",       # index for eddy
    "acqp": "acq",          # acqparams for topup and eddy.
    "slspec": "slspec",     # optional slice spec for eddy.
    "json": "json",         # optional json file for eddy.
    "config": ".cnf"        # optional config file for topup. If not found, the FSL default config b02b0.cnf will be used.
}

# FSL PARAMETERS - adjust as needed.
TOPUP_PARAMS = {
    "nthr": 14,             # --nthr to run topup.
    "jacout": None,         # Default False. 
    "logout": None,         # Default False. 
    "dfout": None,          # Default False.
    "output_dir": None      # all files are saved in the linux working directory by default (None). The corrected files are copied back into main_dir in windows.
    # remaining Topup parameters are set with the config file. You can specify a config file for each patient or a common one in the common folder by placing the .cnf file in the directory.
}


EDDY_PARAMS = {
    "b_range": None,        # None defaults to 50.
    "flm": None,            # ('linear', 'quadratic', 'cubic'). None defaults to 'quadratic'
    "slm": None,            # ('none', 'linear', 'quadratic'). None defaults to 'none'.
    "fwhm": 10,             # Default: 0 mm. Set to 10 for testing.
    "niter": 1,             # Default: 5. Set to 1 for testing.
    "interp": None,         # ('spline', 'trilinear'). None defaults to 'spline'.
    "resamp": None,         # ('jac', 'lsr'). None defaults to 'jac'.
    "fep": None,            # True/False. None defaults to False.
    "nvoxhp": None,         # None defaults to 1000.
    "ff": None,             # [0,10]. None defaults to 10.
    "dont_sep_offs_move": None,  # True/False. None defaults to False.
    "dont_peas": None,      # True/False. None defaults to False.

    "repol": None,          # True/False. None defaults to False. set to True to enable outlier replacement.
    "ol_nstd": None,        # When repol=True; None defaults to 4.
    "ol_nvox": None,        # When repol=True; None defaults to 250.
    "ol_type": None,        # When repol=True; ('sw', 'gw', 'both'). None defaults to 'sw'.
    "ol_ss": None,          # When repol=True; ('sw', 'pooled'). None defaults to 'sw'.
    "ol_pos": None,         # When repol=True; True/False. None defaults to False.
    "ol_sqr": None,         # When repol=True; True/False. None defaults to False.

    "mporder": None,        # Default 0.
    "s2v_niter": None,      # When mporder>0; None defaults to 5.
    "s2v_lambda": None,     # When mporder>0; None defaults to 1.
    "s2v_interp": None,     # When mporder>0; ('trilinear', 'spline'). None defaults to 'trilinear'.

    "estimate_move_by_susceptibility": None,  # True/Flase. None defaults to False.
    "mbs_niter": None,      # When estimate_move_by_susceptibility=True; None defaults to 10.
    "mbs_lambda": None,     # When estimate_move_by_susceptibility=True; None defaults to 10.
    "mbs_ksp": None,        # When estimate_move_by_susceptibility=True; None defaults to 10.

    "cnr_maps": None,       # True/False. None defaults to False. 
    "residuals": None,      # True/False. None defaults to False.
    "data_is_shelled": None,# True/False. None defaults to False.
    "nthr": None,           # --nthr to run eddy. only relevant for CPU!

    "output_dir": None      # all files are saved in the linux working directory by default (None). The corrected files are copied back into original dir in windows.
}

# WSL commands are run through your distro and in whatever directory you specify as your linux_workdir.
fsl = TOPED(

    distribution="Ubuntu-22.04", # your WSL distribution name. you can find it by running 'wsl -l -v' in powershell.
    user="username", # replace with your WSL user.
    linux_workdir=r"\\wsl.localhost\Ubuntu-22.04\home\user\yourfolder"  # replace with a path to a folder in your WSL distribution.
    # yourfolder will be created if it does not exist. 
    # All output files will be saved here. Corrected files from TOPUP and Eddy will be copied back to the patient folders in windows. 
    # linux_workdir will be organised into folders matching your main_dir structure, i.e. for each patient folder in main_dir, a corresponding folder is created in linux_workdir and all processing for that patient is done in that folder.
)





# =======================================================================================================================================================
"""RUNNING LOOP THOUGH FOLDERS IN MAIN_DIR, WITH PARAMTERS SPECIFIED ABOVE"""
# ALL lops are run with the parameters as specified in the configuration section above. parameters are global for the run.
# be careful if/when changing this section below (needs to match with TOPED_fsl_commands.py).


# HELPER functions to find input files based in IDENTIFIERS dict.
def find_file(folder, keyword) -> Optional[str]:
    matches = [f for f in os.listdir(folder) if keyword.lower() in f.lower()]
    if len(matches) == 0:
        return None
    if len(matches) > 1:
        raise RuntimeError(f"Multiple files found for '{keyword}' in {folder}")
    return os.path.join(folder, matches[0])

# function for finding cnf files. 
def find_cnf_file(folder):
    matches = [f for f in os.listdir(folder) if f.lower().endswith(".cnf")]
    if len(matches) == 0:
        return None
    if len(matches) > 1:
        raise RuntimeError(f"Multiple .cnf files found in {folder}! clean this shit up")
    return os.path.join(folder, matches[0])
# function for finding json files.
def find_json_file(folder):
    matches = [f for f in os.listdir(folder) if f.lower().endswith(".json")]
    if len(matches) == 0:
        return None
    if len(matches) > 1:
        raise RuntimeError(f"Multiple .json files found in {folder}!")
    return os.path.join(folder, matches[0])


# searches for the file in the patient folder first, then in the common folder if not found in the patient folder.
def resolve_file(patient_dir, common_dir, key):
    local = find_file(patient_dir, IDENTIFIERS[key])
    if local:
        return local
    if common_dir:
        return find_file(common_dir, IDENTIFIERS[key])
    return None


# main loops start HERE - runs TOPUP and Eddy for each patient folder in main_dir
common_dir = None
if COMMON_FOLDER_NAME:
    _common_path = os.path.join(MAIN_DIR, COMMON_FOLDER_NAME)
    if os.path.isdir(_common_path):
        common_dir = _common_path
    else:
        print("note: no common folder found -> checking compulsory files in remaining folders...")

# Input file check - check all of main_dir, do the files exist for all patients?
# this is so that you wont leeave this overnight and come back to some shit error that could have been prevented. 

print("\n File check: Checking if all required files are found...")
file_check = True

for patient in os.listdir(MAIN_DIR):
    patient_dir = os.path.join(MAIN_DIR, patient)
    if not os.path.isdir(patient_dir) or patient == COMMON_FOLDER_NAME:
        continue

    issues = []

    # Locate files using same logic as the main loop
    b0_path   = find_file(patient_dir, IDENTIFIERS["b0"])
    dwi_path  = find_file(patient_dir, IDENTIFIERS["dwi"])
    mask_path = find_file(patient_dir, IDENTIFIERS["mask"])
    acqp_path   = resolve_file(patient_dir, common_dir, "acqp")
    bvecs_path  = resolve_file(patient_dir, common_dir, "bvec")
    bvals_path  = resolve_file(patient_dir, common_dir, "bval")
    index_path  = resolve_file(patient_dir, common_dir, "index")

    # TOPUP compulsory inputs
    if not b0_path:   issues.append("TOPUP: cannot find b0 file")
    if not acqp_path: issues.append("TOPUP: cannot find acquisition parameters file")

    # EDDY compulsory (only warn if b0 exists, i.e. TOPUP would run)
    if b0_path:
        if not dwi_path:   issues.append("EDDY: cannot find 4D dwi file")
        if not mask_path:  issues.append("EDDY: cannot find mask file")
        if not bvecs_path: issues.append("EDDY: cannot find bvecs file")
        if not bvals_path: issues.append("EDDY: cannot find bvals file")
        if not index_path: issues.append("EDDY: cannot find index file")

    if issues:
        print(f"  FAIL  {patient}:")
        for issue in issues:
            print(f"          - {issue}")
        file_check = False
    else:
        print(f"  OK    {patient}")

if not file_check:
    print("\n WARNING!!!!!!!!! File check failed. Some files cannot be found. You may want to abort and fix the issues. " \
    "\n Consider renaming your files to contain the specified keyword or adjust the IDENTIFIERS dict accordingly. " \
    "\n TOPUP/Eddy will run only for the 'OK' cases.")
else:
    print("\n File check passed — all patients have all compulsory inputs.")


for patient in os.listdir(MAIN_DIR):
    # searches ALL folders in main_dir (except for specified common_folder). -> Attempts to run topup+eddy on all folders in main_dir.
    patient_dir = os.path.join(MAIN_DIR, patient)
    if not os.path.isdir(patient_dir) or patient == COMMON_FOLDER_NAME:
        continue
    print(f"\n \nProcessing folder: {patient}--------------------------------------------------------------")
    patient_id = patient  # this is the name of the folder both in windows and in linux workdir. 

    try:
        # Locate compulsory files - these files should be in the 'patient' directory, not in common.
        b0_path = find_file(patient_dir, IDENTIFIERS["b0"])
        dwi_path = find_file(patient_dir, IDENTIFIERS["dwi"])
        mask_path = find_file(patient_dir, IDENTIFIERS["mask"])
        # these can be in both common and patient dir.
        acqp_path = resolve_file(patient_dir, common_dir, "acqp")
        bvecs_path = resolve_file(patient_dir, common_dir, "bvec")
        bvals_path = resolve_file(patient_dir, common_dir, "bval")
        index_path = resolve_file(patient_dir, common_dir, "index")
        slspec_path = resolve_file(patient_dir, common_dir, "slspec")
        config_path = find_cnf_file(patient_dir)
        if not config_path and common_dir:
            config_path = find_cnf_file(common_dir)
        json_path = find_json_file(patient_dir)
        if not json_path and common_dir:
            json_path = find_json_file(common_dir)

        # Check TOPUP inputs
        if not b0_path:
            print(f" o_O No b0 found in {patient} → Cannot run TOPUP. skipping dataset. Rename your b0 file to contain the specified keyword or adjust the IDENTIFIERS dict accordingly.")
            continue
        if not acqp_path:
            raise RuntimeError(" Missing acquisition parameters (acqp). Please add file or update IDENTIFIERS dict.")

        print(f"      → Running TOPUP :)")
        # RUN TOPUP
        topup_base = fsl.run_topup(
            b0_path=b0_path,
            acq_parameter_path=acqp_path,
            config_file_path=config_path,
            nthr=TOPUP_PARAMS["nthr"],
            logout=TOPUP_PARAMS["logout"],
            jacout=TOPUP_PARAMS["jacout"],
            dfout=TOPUP_PARAMS["dfout"],
            patient_id=patient,
            output_dir=TOPUP_PARAMS["output_dir"] or patient_dir
        )

        # Check EDDY inputs
        missing_eddy = []
        if not dwi_path: missing_eddy.append("dwi")
        if not mask_path: missing_eddy.append("mask")
        if not bvecs_path: missing_eddy.append("bvecs")
        if not bvals_path: missing_eddy.append("bvals")
        if not index_path: missing_eddy.append("index")

        if missing_eddy:
            print(f" o_O Eddy missing compulsory parameters: {missing_eddy} → Cannot run EDDY. Rename your files to contain the respective keywords or adjust the IDENTIFIERS dict accordingly.")
            continue
#
        print(f"      → Running Eddy :)")

        # RUN EDDY
        fsl.run_eddy(
            dwi_path=dwi_path,
            mask_path=mask_path,
            acq_parameter_path=acqp_path,
            index_path=index_path,
            bvecs_path=bvecs_path,
            bvals_path=bvals_path,
            patient_id=patient,
            topup_base=topup_base,

            slspec_path=slspec_path,
            json_path=json_path,
            b_range=EDDY_PARAMS["b_range"],

            flm=EDDY_PARAMS["flm"],
            slm=EDDY_PARAMS["slm"],
            fwhm=EDDY_PARAMS["fwhm"],
            niter=EDDY_PARAMS["niter"],
            interp=EDDY_PARAMS["interp"],
            resamp=EDDY_PARAMS["resamp"],
            fep=EDDY_PARAMS["fep"],
            nvoxhp=EDDY_PARAMS["nvoxhp"],
            ff=EDDY_PARAMS["ff"],
            dont_sep_offs_move=EDDY_PARAMS["dont_sep_offs_move"],
            dont_peas=EDDY_PARAMS["dont_peas"],

            repol=EDDY_PARAMS["repol"],
            ol_nstd=EDDY_PARAMS["ol_nstd"],
            ol_nvox=EDDY_PARAMS["ol_nvox"],
            ol_type=EDDY_PARAMS["ol_type"],
            ol_ss=EDDY_PARAMS["ol_ss"],
            ol_pos=EDDY_PARAMS["ol_pos"],
            ol_sqr=EDDY_PARAMS["ol_sqr"],
            mporder=EDDY_PARAMS["mporder"],
            s2v_niter=EDDY_PARAMS["s2v_niter"],
            s2v_lambda=EDDY_PARAMS["s2v_lambda"],
            s2v_interp=EDDY_PARAMS["s2v_interp"],
        
            estimate_move_by_susceptibility=EDDY_PARAMS["estimate_move_by_susceptibility"],
            mbs_niter=EDDY_PARAMS["mbs_niter"],
            mbs_lambda=EDDY_PARAMS["mbs_lambda"],
            mbs_ksp=EDDY_PARAMS["mbs_ksp"],

            cnr_maps=EDDY_PARAMS["cnr_maps"],
            residuals=EDDY_PARAMS["residuals"],
            data_is_shelled=EDDY_PARAMS["data_is_shelled"],
            
            
            output_dir=EDDY_PARAMS["output_dir"] or patient_dir
        )

        print(f"\n Done. Check your output for {patient} :)")

    except Exception as e:
        print(f"ERROR in {patient}: {str(e)}")