library(tidyverse)
data <- read.csv("test_output.csv", skip=1, col.names=c("Algorithm", "Region", "SNR", "Truth", "Fitted"))
data<-separate_wider_delim(data, cols = Truth, delim = ",", names = c("f", "D", "Dp"))
data$f <- substring(data$f, 2)
data$Dp <- substring(data$Dp, 1, nchar(data$Dp) - 1)
data<-separate_wider_delim(data, cols = Fitted, delim = ",", names = c("f_fitted", "D_fitted", "Dp_fitted"))
data$f_fitted <- substring(data$f_fitted, 2)
data$Dp_fitted <- substring(data$Dp_fitted, 1, nchar(data$Dp_fitted) - 1)
data[c("Algorithm", "Region")] <- sapply(data[c("Algorithm", "Region")], as.factor)
data[c("SNR", "f", "D", "Dp", "f_fitted", "D_fitted", "Dp_fitted")] <- sapply(data[c("SNR", "f", "D", "Dp", "f_fitted", "D_fitted", "Dp_fitted")], as.numeric)
ggplot(data, aes(x=Algorithm)) + geom_boxplot(aes(y=f_fitted)) + geom_boxplot(color="red", aes(y=f)) + facet_grid(SNR ~ Region) + scale_x_discrete(guide = guide_axis(angle = 90)) + ylim(0, 1) + ggtitle("Perfusion fraction grid") + xlab("Perfusion fraction")
ggsave("f.pdf", width = 50, height = 50, units = "cm")
ggplot(data, aes(x=Algorithm)) + geom_boxplot(aes(y=D_fitted)) + geom_boxplot(color="red", aes(y=D)) + facet_grid(SNR ~ Region) + scale_x_discrete(guide = guide_axis(angle = 90)) + ggtitle("Diffusion grid") + xlab("Diffusion")
ggsave("D.pdf", width = 50, height = 50, units = "cm")
ggplot(data, aes(x=Algorithm)) + geom_boxplot(aes(y=Dp_fitted)) + geom_boxplot(color="red", aes(y=Dp)) + facet_grid(SNR ~ Region) + scale_x_discrete(guide = guide_axis(angle = 90)) + ggtitle("Perfusion grid") + xlab("Perfusion")
ggsave("Dp.pdf", width = 50, height = 50, units = "cm")
#why?
ggplot(data, aes(x=Algorithm)) + geom_boxplot(aes(y=D_fitted)) + geom_boxplot(color="red", aes(y=Dp)) + facet_grid(SNR ~ Region) + scale_x_discrete(guide = guide_axis(angle = 90)) + ggtitle("Diffusion grid") + xlab("Diffusion")
ggsave("D_tweak.pdf", width = 50, height = 50, units = "cm")
ggplot(data, aes(x=Algorithm)) + geom_boxplot(aes(y=Dp_fitted)) + geom_boxplot(color="red", aes(y=D)) + facet_grid(SNR ~ Region) + scale_x_discrete(guide = guide_axis(angle = 90)) + ggtitle("Perfusion grid") + xlab("Perfusion")
ggsave("Dp_tweak.pdf", width = 50, height = 50, units = "cm")